import Head from 'next/head';
import { Space_Grotesk } from 'next/font/google';
import { header, homeSection, illustrationSection, main, navLink, title } from '@/styles/home.css';
import { Trail } from '@/components/trail/trail';
import { Logo } from '@/components/logo/logo';
import { Button } from '@/components/button/button';

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${spaceGrotesk.className} ${main}`}>
        <section className={homeSection} data-scroll-section>
          <header className={header}>
            <Logo></Logo>
            <nav>
              <a className={navLink}>about</a>
            </nav>
          </header>
          <Trail open={true} className={title}>
            <span>Constantly,</span>
            <span>innovation</span>
            <span>everywhere.</span>
          </Trail>
          <div>
            <Button>
              View our work
            </Button>
          </div>
        </section>
        <section className={illustrationSection} data-scroll-section>

        </section>
      </main>
    </>
  );
}
